export const Users = [
    {
      id:1,
      profilePicture: "../assets/img/Screenshot.png",
      username: "Ola Ishola",
    },
    {
      id:2,
      profilePicture: "../assets/img/me.jpg",
      username: "Shane Mate",
    },
    {
      id:3,
      profilePicture: "../assets/img/mac.jpeg",
      username: "Aliko Dangote",
    },
    {
      id:4,
      profilePicture: "../assets/img/travel.jpeg",
      username: "Dora Hawks",
    },
    {
      id:5,
      profilePicture: "../assets/img/flower.jpeg",
      username: "Ngolo Kante",
    },
    {
      id:6,
      profilePicture: "../assets/img/per.jpg",
      username: "Shirley Beauchamp",
    },
    {
      id:7,
      profilePicture: "../assets/img/travel.jpeg",
      username: "Travis Bennett",
    },
    {
      id:8,
      profilePicture: "../assets/img/workspace.jpeg",
      username: "Godwin Afolabi",
    },
    {
      id:9,
      profilePicture: "../assets/img/heart.png",
      username: "Fola Mekiota",
    },
    {
      id:10,
      profilePicture: "../assets/img/travel.jpeg",
      username: "Sara Godwin",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "./assets/img/mac.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "./assets/img/flower.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "./assets/img/simple.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "./assets/img/travel.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "./assets/img/per.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "./assets/img/workspace.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "./assets/img/hng.png",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "./assets/img/Screenshot.png",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "./assets/img/travel.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "./assets/img/heart.png",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];